#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --partition=medium
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=256
#SBATCH --hint=multithread
#SBATCH --mem-per-cpu=50M
#SBATCH --time=06:00:00
#SBATCH --output=Output/slurm-%j.out
#SBATCH --error=Output/error-%j.out

module load hyperqueue

# Specify a location and create a directory for the server
export HQ_SERVER_DIR="$SCRATCH/hq-server/$SLURM_JOB_ID"
mkdir -p "$HQ_SERVER_DIR"

# Start the server in the background and wait until it has started
hq server start &
until hq job list &> /dev/null ; do sleep 1 ; done

# Start the workers in the background
srun --overlap --cpu-bind=none --mpi=none hq worker start --manager slurm --on-server-lost finish-running --cpus=$SLURM_CPUS_PER_TASK &
hq worker wait $SLURM_NTASKS

# Submit tasks to workers
hq submit --stdout=none --stderr=none --cpus=$4 --array=$3 ./hq_task $1 $4 $2

# Wait for all tasks to finish
hq job wait all

# Shut down the workers and server
hq worker stop all
hq server stop