#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --output=Output/slurm-%j-%a.out
#SBATCH --error=Output/error-%j-%a.out

srun ./ChargedCurrentDIS $1 --nthreads $SLURM_CPUS_PER_TASK --pdf $2 --variation-start $SLURM_ARRAY_TASK_ID --variation-end $SLURM_ARRAY_TASK_ID --output $CC_DIR