#!/bin/bash

#SBATCH --job-name=dis
#SBATCH -o Output/dis.txt
#SBATCH --array=0-7
#SBATCH --ntasks=1

ARGS=(dis.differential.charm.errors dis.differential.total.errors dis.integrated.charm.errors dis.integrated.total.errors dis.differential.charm.scales dis.differential.total.scales dis.integrated.charm.scales dis.integrated.total.scales)

srun ./ChargedCurrentDIS ${ARGS[$SLURM_ARRAY_TASK_ID]} --nthreads $SLURM_CPUS_PER_TASK
